### ISSUE TITLE
Inconsistent behavior of yaml output formatting

### ISSUE THREAD

**Issue by kinghrothgar** [kubecfg/kubecfg#320]
I am using kubecfg to generate yaml from jsonnet. I'm trying to figure out an inconsistency in the yaml output. I am using jsonnet `std.manifestYamlDoc` to generate yaml for a field. In one case, the yaml output is "pretty printed" like so:

```yaml
---
apiVersion: v1
data:
  asdf.yaml: |-
    "apm_config":
      "enabled": true
      "receiver_port": 8126
      "receiver_socket": "/var/run/datadog/apm.socket"
    "cloud_provider_metadata":
...
```

In another case, it outputs a string with `\n`:

```yaml
---
apiVersion: v1
data:
  config.yaml: "\"resourceRules\":\n  \"cpu\":\n    \"containerLabel\": \"container_name\"\n
    \   \"containerQuery\": |\n      sum by (<<.GroupBy>>) (\n        irate(\n          blahblahblahblah..."
```

When I use jsonnet directly, it always does the second (string with `\n`), so I think this has something to do with how kubecfg is doing it's yaml output? I prefer the first version that using `-|` but I can't figure out what causes the different output formats. Any suggestions on how to debug this further?
