### ISSUE TITLE
Create an "official" setup-kubecfg github action

### ISSUE THREAD

**Issue by mkmik** [kubecfg/kubecfg#456]
It would be nice if Github Action users could effortlessly download the `kubecfg` binary in their pipelines:

```yaml
 uses: kubecfg/setup-kubecfg
```

The setup action should allow the user to specify a version if they don't want the latest.

```yaml
 uses: kubecfg/setup-kubecfg
 with:
   version: v1.36.0
```

There is a community action in https://github.com/kingdonb/kubecfg/tree/main/action
But it would be nice if we could have an official one hosted in the kubecfg repo.
