### ISSUE TITLE
Segfault on update of deeply nested custom resource with `x-kubernetes-preserve-unknown-fields: true` 

### ISSUE THREAD

**Issue by muxmuse** [kubecfg/kubecfg#99]
This doesn't seem to be a bug in kubecfg, but it appears with `kubecfg update` but not with `kubectl apply -f`, thus reporting it here as known.

Nesting-level and usage of an array seem to be crucial to reproduce the error. Also, the error only occurs when the resource already exists in the cluster.

Minimal (afaik) example:

``` yaml
# crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mres.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            a:
              type: object
              properties:
                b:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: mres
    singular: mre
    kind: Mre
```

``` yaml
# resource.yaml
apiVersion: example.com/v1
kind: Mre
metadata:
  name: mre
a:
  b:
    c:
      d:
        e:
          - f: ''
```

``` bash
kubecfg update crd.yaml
kubecfg update resource.yaml
kubecfg update resource.yaml
```

gives segfault:
```
...
k8s.io/apimachinery/pkg/util/strategicpatch.handleSliceDiff({0x10408fd48, 0x1}, {0x140001e98d0, 0x1, 0x1}, {0x140001e97d0, 0x1, 0x1}, 0x1400011c7d8?, {0x0?, ...}, ...)
	/.../pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/strategicpatch/patch.go:306 +0x5c
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0x1042ff9c8?, 0x14001190900, {0x0, 0x0}, {0xb8?, 0x85?, 0x96?, 0x4?})
...
```
